test: employees tests
LucasTI79/meli_bootcamp_go_w2-1 pull request #26
Opened 2023-06-23 21:21 UTC by AdrianaMeyer

Implementation of tests for requirement employees - Service and controller

2023-06-24 22:14 UTC, vraissa approved these changes
Muito bom!

2023-06-26 12:25 UTC, oaugustocezar requested changes

2023-06-26 12:25 UTC, oaugustocezar commented on go.sum
> +github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578/go.mod h1:uGdkoq3SwY9Y+13GIhn11/XLaGBb4BfwItxLd5jeuXE=
acho que dá pra tirar essa alteração do go.sum

2023-06-26 12:29 UTC, davidsonbrsilva approved these changes

2023-06-26 12:39 UTC, AdrianaMeyer commented on go.sum
> +github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578/go.mod h1:uGdkoq3SwY9Y+13GIhn11/XLaGBb4BfwItxLd5jeuXE=
Ajustei =)

2023-06-26 12:43 UTC, oaugustocezar approved these changes

2023-06-26 12:51 UTC, merged